import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "../components/Header/Header";
import Navigation from "@/components/nav/nav";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "News App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

       <Header /> 
        </body>
    </html>
  );
}
